sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libsecret-1-dev

services: docker

matrix:
  # abi versions https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/abi_crosswalk.json
  include:
    # linux
    - os: linux   # abi 57
      env: NODE_VERSION="10.15.2" CXX="g++-7"
    # os x x86
    - os: osx     # abi 64
      env: NODE_VERSION="10.15.2" CXX="clang"

before_install:
  - cd $TRAVIS_BUILD_DIR
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker build --rm --build-arg NODE_VERSION=$NODE_VERSION -t centos6_builder -f Dockerfile .
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
      source ~/.nvm/nvm.sh
      nvm install $NODE_VERSION
      nvm use $NODE_VERSION
      export PATH="./node_modules/.bin/:$PATH"
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run -v `pwd`:/build -it --rm centos6_builder sh 'cd ctags && npm install && npm run build';
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pushd ctags
        npm install
        npm run build
      popd
    fi
script:
  - |
    pushd ctags
      [[ -z "$ELECTRON" ]] && npm test
      node-pre-gyp package testpackage
    popd

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/

deploy:
  provider: releases
  api_key:
    secure: Jaf7wg4fLcn1rcysdKOH4xQG7On2o7g4xarjFszjCJFPAIZHHaIPqQHeS+jlhiG/9Wt/3XbNVQRctlnCIK5MyEz2c8AKnLnMcBpgd276NUfx87PomjhZnpqXCB4Txi9Y/UHvmIo7gVrUUWo38XDpIJ7dbe9f8cNzQsMi9RZfsg/h9MIySJPyYRq4bqrM5OxfADDrLRhBHEq+QcJpYsZJ5zKyTig2LvFFoPPVdf+y5HK6oQDMKUTu5yVVYBr8ORPvHzMr8PLVbJLvsyxzReJ47eF/B8AF+r4I+pxsu6Jhpa7KPa8cs32uaBnzAj+DL1GgomKqG8Y4fJ6YuhcDKdpIemB7Bkt6nO2JSMuOYdBpo7LvgAPKqj2RGEBOw6Os7SCSragEls3UEszRt2oIRVP8VcAq1R43T0RuFz69+2YOy99/v3aRTUC86gcU6A0CvrxqF7N4vAomKJIZJcIFEg4DwoQqWh5vscLkpdTx0wkWfNlPzOFMOk3pGZ9JIZvbR68EheP/cJVkZqIx3+OUcCDFqLKhLPxp67Qvj9Zv5B7W21P8ott6D3aEn1+LNmGmEm4yPOk2RQFDprqA/oDGAcmbUlXqa9YdALjHHaneI9A+czrK8iv6Ik730nYeDYih3MRhLkWDHTcblTdJHHZUyBZdkxBIzKCYviwaTi6CxZW0McQ=
  skip_cleanup: true
  file_glob: true
  file: "*/build/stage/*.tar.gz"
  overwrite: true
  on:
    repo: elastic/node-ctags
    tags: true
