image: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "10.15.2"

matrix:
  fast_finish: true

platform:
  - x64

configuration:
  - Release

install:
  - ps: |
      Install-Product node $env:nodejs_version x64
      if ($env:ELECTRON) {
        $env:npm_config_target=$env:ELECTRON
        $env:npm_config_disturl="https://atom.io/download/electron"
        $env:npm_config_runtime="electron"
        $env:npm_config_build_from_source="true"
      }
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\ctags
      npm install
      npm run build

test_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%\ctags
      IF NOT DEFINED ELECTRON (npm test)
      node_modules/.bin/node-pre-gyp package testpackage
      
build: off

artifacts:
  - path: '**\build\stage\*.tar.gz'

deploy:
  description: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: AfJEZz4Zv9OTyO2KxHZ3nF6JSFu0gjfKJKxS/WIyb3wInsmCAeBKlzunN5F1q7DU
  artifact: /.*\.tar\.gz/
  force_update: true
  on:
    appveyor_repo_tag: true
